version: '3.8'

services:
  qr-reader-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: qr-reader-api:latest
    container_name: qr-reader-api
    restart: unless-stopped
    environment:
      - PORT=8000
      - API_TOKEN=${API_TOKEN:-line-connect-api-token-2025}
    expose:
      - "8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
    networks:
      - qr-reader-network

  nginx:
    image: nginx:alpine
    container_name: qr-reader-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - qr-reader-api
    networks:
      - qr-reader-network

networks:
  qr-reader-network:
    driver: bridge
