version: '3.8'

services:
  qr-reader-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: qr-reader-api:latest
    container_name: qr-reader-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - API_TOKEN=${API_TOKEN:-line-connect-api-token-2025}
    volumes:
      - ./:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
